# Generated by Django 5.2.5 on 2025-08-10 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('contact_email', models.CharField(max_length=200)),
                ('organizer_name', models.CharField(default='Organizer name', max_length=200)),
                ('organizer_bic', models.CharField(default='GABBBEBB', max_length=16)),
                ('bank_account', models.CharField(default='BE00 0000 0000 0000', max_length=32)),
                ('disabled', models.BooleanField(default=False)),
                ('full_payment_confirmation_template', models.CharField(default='<p>Hi,</p><p>Thank you for your payment for <a class="link-primary" href="%reservation_url%">your reservation</a>.</p><p>Greetings,<br>--&nbsp;<br>Signature</p>', max_length=1024)),
                ('partial_payment_confirmation_template', models.CharField(default='<p>Hi,</p><p>Thank you for your payment for <a class="link-primary" href="%reservation_url%">your reservation</a>.</p><p>You can wire the remaining %remaining_amount_in_euro% € to %organizer_name% (%bank_account%, %organizer_bic%) with the communication <pre>%formatted_bank_id%</pre>.</p><p>Greetings,<br>--&nbsp;<br>Signature</p>', max_length=1024)),
                ('max_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BaseReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(choices=[(None, ''), ('Mr', 'Man'), ('Mme', 'Woman'), ('Mlle', 'Miss')], default='', max_length=20)),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('accepts_rgpd_reuse', models.BooleanField()),
                ('total_due_in_cents', models.IntegerField()),
                ('extra_comment', models.CharField(blank=True, default='', max_length=200)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bank_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('base_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='core.baseevent')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField()),
                ('amount_in_cents', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=512)),
                ('src_id', models.CharField(blank=True, max_length=32)),
                ('bank_ref', models.CharField(max_length=32)),
                ('other_account', models.CharField(blank=True, max_length=40)),
                ('other_name', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(max_length=16)),
                ('active', models.BooleanField(db_default=True)),
                ('srh_bank_id', models.CharField(blank=True, max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['src_id'], name='core_paymen_src_id_fc3e2d_idx'), models.Index(fields=['bank_ref'], name='core_paymen_bank_re_322155_idx'), models.Index(fields=['srh_bank_id'], name='core_paymen_srh_ban_178649_idx')],
                'constraints': [models.UniqueConstraint(fields=('bank_ref',), name='core_payment_unique_bank_ref')],
            },
        ),
        migrations.CreateModel(
            name='ReservationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_sent_timestamp', models.DateTimeField(null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.payment')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.basereservation')),
            ],
        ),
    ]
