# Generated by Django 5.2.5 on 2025-08-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField()),
                ('amount_in_cents', models.IntegerField()),
                ('comment', models.CharField(blank=True, max_length=512)),
                ('src_id', models.CharField(blank=True, max_length=32)),
                ('bank_ref', models.CharField(max_length=32)),
                ('other_account', models.CharField(blank=True, max_length=40)),
                ('other_name', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(max_length=16)),
                ('active', models.BooleanField(db_default=True)),
                ('srh_bank_id', models.CharField(blank=True, max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['src_id'], name='core_paymen_src_id_fc3e2d_idx'), models.Index(fields=['bank_ref'], name='core_paymen_bank_re_322155_idx'), models.Index(fields=['srh_bank_id'], name='core_paymen_srh_ban_178649_idx')],
                'constraints': [models.UniqueConstraint(fields=('bank_ref',), name='unique_bank_ref')],
            },
        ),
    ]
