# Generated by Django 5.2.5 on 2025-08-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservationpayment',
            constraint=models.UniqueConstraint(models.F('payment'), name='core_reservationpayment_unique_payment'),
        ),
    ]
