# Generated by Django 5.2.5 on 2025-09-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservationpayment_core_reservationpayment_unique_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseevent',
            name='extra_info',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
