# Generated by Django 5.1.4 on 2024-12-15 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('accepts_rpgd_reuse', models.BooleanField()),
                ('attends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.event')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=200)),
                ('price_in_cents', models.PositiveIntegerField()),
                ('available_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.event')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=200)),
                ('column_header', models.CharField(max_length=200)),
                ('short_text', models.CharField(max_length=200)),
                ('choices', models.ManyToManyField(to='ital.choice')),
            ],
        ),
    ]
