# Generated by Django 5.2.5 on 2025-08-10 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('contact_email', models.CharField(max_length=200)),
                ('organizer_name', models.CharField(default='Organizer name', max_length=200)),
                ('organizer_bic', models.CharField(default='GABBBEBB', max_length=16)),
                ('bank_account', models.CharField(default='BE00 0000 0000 0000', max_length=32)),
                ('disabled', models.BooleanField(default=False)),
                ('full_payment_confirmation_template', models.CharField(default='<p>Hi,</p><p>Thank you for your payment for <a class="link-primary" href="%reservation_url%">your reservation</a>.</p><p>Greetings,<br>--&nbsp;<br>Signature</p>', max_length=1024)),
                ('partial_payment_confirmation_template', models.CharField(default='<p>Hi,</p><p>Thank you for your payment for <a class="link-primary" href="%reservation_url%">your reservation</a>.</p><p>You can wire the remaining %remaining_amount_in_euro% € to %organizer_name% (%bank_account%, %organizer_bic%) with the communication <pre>%formatted_bank_id%</pre>.</p><p>Greetings,<br>--&nbsp;<br>Signature</p>', max_length=1024)),
                ('max_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=200)),
                ('price_in_cents', models.PositiveIntegerField()),
                ('available_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.event')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=200)),
                ('display_text_plural', models.CharField(max_length=200)),
                ('column_header', models.CharField(max_length=200)),
                ('short_text', models.CharField(max_length=200)),
                ('dish', models.CharField(choices=[('dt0starter', 'Dt0Starter'), ('dt1main', 'Dt1Main'), ('dt2dessert', 'Dt2Dessert')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('choices', models.ManyToManyField(to='ital.choice')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civility', models.CharField(choices=[(None, ''), ('Mr', 'Man'), ('Mme', 'Woman'), ('Mlle', 'Miss')], default='', max_length=20)),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('accepts_rgpd_reuse', models.BooleanField()),
                ('total_due_in_cents', models.IntegerField()),
                ('places', models.IntegerField()),
                ('extra_comment', models.CharField(blank=True, default='', max_length=200)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bank_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.event')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationItemCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.choice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.item')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.reservation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('choice_id', 'item_id', 'reservation_id'), name='reservation*item*choice')],
            },
        ),
        migrations.CreateModel(
            name='ReservationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_sent_timestamp', models.DateTimeField(null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.payment')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ital.reservation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('payment'), name='ital_reservationpayment_unique_payment')],
            },
        ),
    ]
