# Generated by Django 5.2.5 on 2025-08-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('base_event_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', serialize=False, to='core.baseevent')),
            ],
            options={
                'proxy': False,
            },
            bases=('core.baseevent',),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=200)),
                ('price_in_cents', models.PositiveIntegerField()),
                ('available_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', related_query_name='%(app_label)s_%(class)ss', to='ital.event')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.CharField(max_length=200)),
                ('display_text_plural', models.CharField(max_length=200)),
                ('column_header', models.CharField(max_length=200)),
                ('short_text', models.CharField(max_length=200)),
                ('dish', models.CharField(choices=[('dt0starter', 'Dt0Starter'), ('dt1main', 'Dt1Main'), ('dt2dessert', 'Dt2Dessert')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('choices', models.ManyToManyField(to='ital.choice')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('base_reservation_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', serialize=False, to='core.basereservation')),
                ('places', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', related_query_name='%(app_label)s_%(class)ss', to='ital.event')),
            ],
            bases=('core.basereservation',),
        ),
        migrations.CreateModel(
            name='ReservationItemCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.choice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.item')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.reservation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('choice_id', 'item_id', 'reservation_id'), name='ital_reservationitemcount_reservation*item*choice')],
            },
        ),
    ]
