# Generated by Django 5.1.4 on 2024-12-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ital', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Reservation',
        ),
    ]
