# Generated by Django 5.1.4 on 2024-12-22 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ital', '0002_rename_customer_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='accepts_rpgd_reuse',
            new_name='accepts_rgpd_reuse',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='attends',
        ),
        migrations.AddField(
            model_name='reservation',
            name='civility',
            field=models.CharField(choices=[(None, ''), ('Mr', 'Man'), ('Mme', 'Woman')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_due_in_cents',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReservationItemCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.choice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.item')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ital.reservation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('choice_id', 'item_id', 'reservation_id'), name='reservation*item*choice')],
            },
        ),
    ]
