# Generated by Django 5.1.4 on 2024-12-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ital', '0003_rename_accepts_rpgd_reuse_reservation_accepts_rgpd_reuse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='places',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
