# Generated by Django 5.1.4 on 2025-01-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ital', '0007_reservation_extra_comment_alter_item_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.CharField(default='dont-spam-me@example.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='civility',
            field=models.CharField(choices=[(None, ''), ('Mr', 'Man'), ('Mme', 'Woman')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
