# Generated by Django 5.1.4 on 2025-01-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ital', '0008_event_contact_email_alter_reservation_civility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bank_account',
            field=models.CharField(default='BE00 0000 0000 0000', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='full_payment_confirmation_template',
            field=models.CharField(default='<p>Hi,</p><p>Thank you for your payment for <a href="%reservation_url%">your reservation</a>.</p><p>Greetings,<br>--&nbsp;<br>Signature</p>', max_length=1024),
        ),
        migrations.AddField(
            model_name='event',
            name='max_seats',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_bic',
            field=models.CharField(default='GABBBEBB', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(default='Organizer name', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='partial_payment_confirmation_template',
            field=models.CharField(default='<p>Hi,</p><p>Thank you for your payment for <a href="%reservation_url%">your reservation</a>.</p><p>You can wire the remaining %remaining_amount_in_euro% € to %organizer_name% (%bank_account%, organizer_bic%) with the communication <pre>%formatted_bank_id%</pre>.</p><p>Greetings,<br>--&nbsp;<br>Signature</p>', max_length=1024),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='civility',
            field=models.CharField(choices=[(None, ''), ('Mr', 'Man'), ('Mme', 'Woman'), ('Mlle', 'Miss')], default='', max_length=20),
        ),
    ]
