# Generated by Django 5.1.4 on 2025-01-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ital', '0009_event_bank_account_event_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display_text_plural',
            field=models.CharField(default='s', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
