# Generated by Django 5.1.4 on 2025-01-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ital', '0010_item_display_text_plural_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ital.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='extra_comment',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
