# Generated by Django 5.1.4 on 2025-01-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ital', '0011_reservation_event_alter_reservation_extra_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='bank_id',
            field=models.CharField(default='123', editable=False, max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
