# Generated by Django 5.1.4 on 2025-02-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ital', '0012_reservation_bank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='full_payment_confirmation_template',
            field=models.CharField(default='<p>Hi,</p><p>Thank you for your payment for <a class="link-primary" href="%reservation_url%">your reservation</a>.</p><p>Greetings,<br>--&nbsp;<br>Signature</p>', max_length=1024),
        ),
        migrations.AlterField(
            model_name='event',
            name='partial_payment_confirmation_template',
            field=models.CharField(default='<p>Hi,</p><p>Thank you for your payment for <a class="link-primary" href="%reservation_url%">your reservation</a>.</p><p>You can wire the remaining %remaining_amount_in_euro% € to %organizer_name% (%bank_account%, organizer_bic%) with the communication <pre>%formatted_bank_id%</pre>.</p><p>Greetings,<br>--&nbsp;<br>Signature</p>', max_length=1024),
        ),
    ]
