# Generated by Django 5.1.4 on 2025-02-09 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ital', '0013_alter_event_full_payment_confirmation_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_sent_timestamp', models.DateTimeField(null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.payment')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ital.reservation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('payment'), name='unique_payment')],
            },
        ),
    ]
