# Generated by Django 5.2.5 on 2025-08-10 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('base_event_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(class)s_set', related_query_name='%(app_label)s_%(class)ss', serialize=False, to='core.baseevent')),
            ],
            options={
                'proxy': False,
            },
            bases=('core.baseevent',),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_cents', models.PositiveIntegerField()),
                ('display_text', models.CharField(max_length=200)),
                ('display_text_plural', models.CharField(max_length=200)),
                ('column_header', models.CharField(max_length=200)),
                ('available_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', related_query_name='%(app_label)s_%(class)ss', to='concert.event')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('base_reservation_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(class)s_set', related_query_name='%(app_label)s_%(class)ss', serialize=False, to='core.basereservation')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', related_query_name='%(app_label)s_%(class)ss', to='concert.event')),
            ],
            options={
                'verbose_name': 'Réservation concert',
                'verbose_name_plural': 'Réservations concert',
            },
            bases=('core.basereservation',),
        ),
        migrations.CreateModel(
            name='ReservationChoiceCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.choice')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concert.reservation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('choice_id', 'reservation_id'), name='concert_reservationchoicecount_reservation*choice')],
            },
        ),
    ]
